services:
  db:
    profiles: ["local-db"]
    image: postgres:16.11-alpine3.23
    container_name: sakura-id-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accountdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    networks:
      - shared-sakura-db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}

volumes:
  postgres_data:

networks:
  shared-sakura-db:
    external: true
